server:
  port: 8101
  servlet:
    context-path: /register

spring:
  application:
    name: FEBS-Register
    #访问Eureka服务的受保护资源所需的用户名和密码
  security:
    user:
      name: febs
      password: 123456
    #防止启动的时候将抛出异常：Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource
    #could be configured.
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  boot:
    admin:
      client:
        #SBA服务端地址；
        url: http://localhost:8106
        username: root
        password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    #是否从Eureka服务端获取服务信息
    fetch-registry: false
    #微服务更新实例信息的变化到Eureka服务端的间隔时间
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
#SpringBootAdmin客户端的信息
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  #将客户端的所有监控端点都暴露给SBA服务端
  endpoints:
    web:
      exposure:
        include: "*"
  #将客户端的健康信息总是显示
  endpoint:
    health:
      show-details: always